[package]
name = "fnorm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.5.58", features = ["derive"] }
walkdir = "2.5.0"
image = "0.25"
serde = { version = "1", features = ["derive"] }
toml = "0.8"